UNIX domain socket support for GSB
golemfactory/ya-service-bus pull request #4
Opened 2021-02-09 16:18 UTC by Wiezzel

2021-02-10 08:07 UTC, mfranciszkiewicz requested changes

2021-02-10 08:07 UTC, mfranciszkiewicz commented on crates/router/src/lib.rs
> +use tokio::net::{TcpListener, TcpStream, UnixListener, UnixStream};
Not platform independent

2021-02-11 09:46 UTC, mfranciszkiewicz approved these changes

2021-02-11 09:47 UTC, mfranciszkiewicz submitted a review, later dismissed

2021-02-11 12:24 UTC, maaktweluit approved these changes
LGTM!

2021-02-11 15:26 UTC, Wiezzel commented
@mfranciszkiewicz Issue with ya-provider resolved by setting `DEFAULT_GSB_URL` to `unix:/tmp/yagna.sock` on UNIX.

2021-02-11 15:28 UTC, mfranciszkiewicz approved these changes

2021-02-15 12:47 UTC, Wiezzel commented
@maaktweluit Bump

2021-02-15 14:34 UTC, maaktweluit approved these changes
Had reviewed this already last thursday :S 

LGTM!

Should this go to `payments/beta-1` or `release/v0.6` to keep in sync with yagna?

2021-02-15 14:49 UTC, merged